export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DELETE_FAVORITE = 'DELETE_FAVORITE';

export const WAGASHI_LOADING = 'WAGASHI_LOADING';
export const ADD_WAGASHI = 'ADD_WAGASHI';
export const WAGASHI_FAILED = 'WAGASHI_FAILED';

export const SUPPLIERS_LOADING = 'SUPPLIERS_LOADING';
export const ADD_SUPPLIERS = 'ADD_SUPPLIERS';
export const SUPPLIERS_FAILED = 'SUPPLIERS_FAILED';